FROM docker.io/library/alpine:latest AS vuetorrent
RUN apk add curl jq
RUN curl -Ssf --header "X-GitHub-Api-Version:2022-11-28" \
    https://api.github.com/repos/WDaan/VueTorrent/releases/latest \
    | jq -r '.assets[] | select(.name == "vuetorrent.zip") | .browser_download_url' \
    | xargs wget -O /tmp/vuetorrent.zip
RUN unzip /tmp/vuetorrent.zip -d /tmp/webui
RUN cd /tmp/webui && mv * /webui

FROM docker.io/library/alpine:latest AS matui
RUN apk add curl jq
RUN curl -Ssf --header "X-GitHub-Api-Version:2022-11-28" \
    https://api.github.com/repos/bill-ahmed/qbit-matUI/releases/latest \
    | jq -r '.assets[] | select(.name | test("Unix")) | .browser_download_url' \
    | xargs wget -O /tmp/matui.zip
RUN unzip /tmp/matui.zip -d /tmp/webui
RUN cd /tmp/webui && mv * /webui

#include "Dockerfile"
ARG FLAVOR
COPY --from=$FLAVOR /webui /opt/webui
ENV WEBUI_ALTERNATIVE=true
