name: Build
on:
  push:
  schedule:
  - cron: '0 3 * * *'
jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: ["", "matui", "vuetorrent"]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      id: build
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ github.repository }}
        tags: ${{ matrix.flavor == '' && 'latest' || matrix.flavor }}
        build-args: FLAVOR=${{ matrix.flavor }}
        containerfiles: ${{ matrix.flavor == '' && 'Dockerfile' || 'Dockerfile.in' }}
        platforms: linux/amd64
    - name: Push
      if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build.outputs.image }}
        tags: ${{ steps.build.outputs.tags }}
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
